---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env-front
type: Opaque
data:
  VITE_API_URL: {{ .Values.deployments.front.env.VITE_API_URL | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env-back
type: Opaque
data:
  CORS: {{ .Values.deployments.back.env.CORS | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecrets.registry .Values.imagePullSecrets.username .Values.imagePullSecrets.password .Values.imagePullSecrets.email (printf "%s:%s" .Values.imagePullSecrets.username .Values.imagePullSecrets.password | b64enc)) | b64enc }}
