---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env-front
type: Opaque
data:
  VITE_API_URL: {{ .Values.deployments.front.env.VITE_API_URL | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env-back
type: Opaque
data:
  CORS: {{ .Values.deployments.back.env.CORS | b64enc }}
