apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lestencrypt 
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
